### ISSUE TITLE
⚠️ Information: Future card configuration changes.

### ISSUE THREAD

**Issue by thomasloven** [finity69x2/light-brightness-preset-row#12]
Hi.

A change in how lovelace cards are set up in Home Assistant 0.105 increases performance, but enables cards to accidentally modify their own configuration in the loaded lovelace configuration.

I'm going through the cards in the HACS default repository, and noticed that your card may be susceptible to this. Looking through your code it seems you may modify parts of the config object passed to your card in `setConfig`.

The result could be that your card does not work well with the GUI editors or that parts of the configuration start showing up multiple times.

At some point in the future, it is likely that the configuration will be frozen before being passed to `setConfig`. At this point, your card will fail entirely when it tries to modify the configuration object.

There are several ways to fix/protect agains this problem.

The best is to restructure `setConfig` such that the configuration is never modified.
Other alternatives are to make a copy of the configuration and work on that instead.

```javascript
setConfig(config) {
  config = { ...config }; // This works for simple configurations not containing arrays or objects
...
```
```javascript
import { deepClone } from "deep-clone-simple";
// https://github.com/balloob/deep-clone-simple

setConfig(config) {
  config = deepClone(config); // This is a safe and fast method
...
```
or
```javascript
setConfig(config) {
  config = JSON.parse(JSON.stringify(config)); // This uses built-in functions, but may be slower than deepClone
  ...
```

Please note that I have not tested your card agains Home Assistant 0.105 or later, but just quickly looked through the code. If I'm mistaken in my assessment, I appologize for taking your time.

See thomasloven/hass-config#6 for more info.

**Comment by finity69x2** [comment]
@thomasloven 

Thanks for the heads up.

But as of right now the plugin works in v105. However, I'm happy toaddress this to future-proof it.

I've tried to add the deepClone as recommended but the browser complains when I run the plug-in with that line added.

error is:

"Uncaught SyntaxError: Unexpected token '{' "

going by the usage instructions at baloob's github link it says to use:

```
import deepClone from 'deep-clone-simple';
```

but then that complains too:

"Uncaught SyntaxError: Unexpected identifier"

I'm really not much of a UI programmer so I'm not sure what I'm doing wrong.

I haven't tried the third option yet since I figured I'd try the "safe and fast" way first.

thanks for the help. :)

**Comment by thomasloven** [comment]
I've taken a second look, and it seems your card is actually ok. You are not overwriting the configuration. What threw me off was the lines
```javascript
this._config = config;
		
		this._config = {
```
where it seems you write `this._config` and then immediately overwrite something in it. But as you're redefining the entire object, it should be fine.

Last time, I had 140+ repos to go through, and took the "better safe than sorry" approach of rather flagging too many repos than too few.

My apologies for the inconvenience.

**Comment by finity69x2** [comment]
No problem at all. 

Like I said, I'm not a real programmer so I'm sure I've got a bunch of stuff in there that isn't necessary. that's what happens when you cobble stuff together by trial and error until it works. :)

I'm still not sure I know what I was doing wrong above tho. It might be something to clarify in your posts to others repo's.

**Comment by thomasloven** [comment]
![real programmers](https://user-images.githubusercontent.com/1299821/74593435-91505c00-502b-11ea-9709-fb56072ac775.jpg)
