### ISSUE TITLE
Feature Request - Button Order

### ISSUE THREAD

**Issue by hathalud** [finity69x2/light-brightness-preset-row#13]
I really like how this works and I really appreciate that you made it. Thank you for your hard work in producing this card. To me, I think the order of the buttons should be the other way... Off, then Low, Med and High. Might you come up with a way to define the order if so desired? Again, Thanks for all your fantastic work on this card.

**Comment by finity69x2** [comment]
I know it doesn't seem like it but I've been trying to come up with a way to allow the user to rearrange the button order but I haven't been able to.

However, since I have a few of these cards now and the binary buttons should logically be reversed "off - on" instead of "on - off" to make them all match with the other items in HA where the control moves to the right when on I might be tempted to just switch them all around and make it "off - low - med - high".

I think I'll ask in the forum thread to see what other users think about it and make the decision based on that feedback.

**Comment by jkread** [comment]
I agree with the off on the left approach for all.  I like and use all your entity rows but modify them to change the button order.

**Comment by finity69x2** [comment]
this feature is now included in v1.7.
