### ISSUE TITLE
Feature Request:  Optional 5th Button

### ISSUE THREAD

**Issue by magnetic157** [finity69x2/light-brightness-preset-row#24]
I really want to use your cards for lights and fans but Lutron Caseta has 5 presets (Off, 25%, 50%, 75%, 100%).  I know you said in a previous request on the fan card that you didn't want to add additional buttons because someone asked you to make 10, but I don't see the harm in adding one additional button that would make your card compatible with the Lutron Caseta line.  

It's a very popular line of smart switches and I think a lot of people other than me would benefit from this.  If you make it so this extra button can be hidden then everyone benefits. 

Hoping you will reconsider!

**Comment by finity69x2** [comment]
First, I'm not sure if this plugin could be used to set brightness as percentages. Right now it's using brightness in a range of 0 - 255. Not in brightness_pct of 0 - 100%.

But if you can use "brightness" instead of "brightness_pct" then...

Right now I have the settings as "low", "medium" & "high" (by default corresponding to 43, 128 & 213) .

If you can give me a reasonable suggestion in which I can add a 4th setting in between "low" & "high" that can easily describe that 4th setpoint without needing to change the names of the other setpoints then I will reconsider.

I really don't want to change any settings as they are now to cause a breaking change for existing users by the addition of an optional 4th setpoint.

optimally it makes sense logically and programatically to make the middle setpoint button the optionally additional button. But if you have 4 setpoints there is no "middle setpoint". if you have 43, 128 & 213 then obviously 128 is the middle but if you have 64, 128, 192, 255 then which setpoint becomes the middle - 128 or 192? if you hide 128 then the setpoints become 64, 192 255. If you hide 192 then they become 64, 128 & 255. Either way you have a large jump over the "missing" setpoint.

I honestly don't have any good idea on how to handle it where it makes for a good user experience using the default setpoints without any breaking changes.
