### ISSUE TITLE
Issues controlling light with dim and temp options

### ISSUE THREAD

**Issue by bobloadmire** [finity69x2/light-brightness-preset-row#28]
I have a Wyze Bulb connected, and in the default HA control panel, it gives me brightness and temperature options as usual, and they work as expected.
When I make a preset row pointing to this entity, I cannot control the brightness. Oddly, if I use the HA control panel to change the brightness, the preset row updates to show closest preset, E.G. 50% brightness, the Med button lights up. So it's reading values fine but it's not setting values. Is this related to the fact that the bulb also has temperature control as well? 

Also, the Off button on the entity row works fine. Weird.

**Comment by finity69x2** [comment]
which service data does your light use to change the brightness? brightness or brightness_pct?

This plug-in uses the "brightness" option to set the brightness instead of the brightness_pct.

Like this:

```
service: light.turn_on
data:
  brightness: 43
```

I assumed all lights supported either method so I never thought there would be a conflict between the two.
