### ISSUE TITLE
Error after Update to Home Assistant 2023.5.0

### ISSUE THREAD

**Issue by ericreich** [finity69x2/light-brightness-preset-row#35]
I am getting the following error while trying to load this module in Lovelace.  Ideas?

Logger: frontend.js.latest.202305031
Source: components/system_log/__init__.py:257
First occurred: 6:37:33 PM (16 occurrences)
Last logged: 6:39:24 PM

http://homeassistant.myreichfamily.com:8123/frontend_latest/app-8b3iZYoMH1E.js:2:30103 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "light-with-profiles" has already been used with this registry
http://192.168.1.85:8123/hacsfiles/fan-control-entity-row/fan-control-entity-row.js?hacstag=19166315023:9:28 Uncaught ReferenceError: Polymer is not defined
http://192.168.1.85:8123/hacsfiles/light-brightness-preset-row/light-brightness-preset-row.js?hacstag=22686296922:9:40 Uncaught ReferenceError: Polymer is not defined
http://192.168.1.85:8123/hacsfiles/fan-percent-button-row/fan-percent-button-row.js?hacstag=34575320520:9:35 Uncaught ReferenceError: Polymer is not defined
http://192.168.1.85:8123/lovelace/default_view:0:0 Uncaught

**Comment by froman753** [comment]
Appears to be related to this:
https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

Edit: The developer was not sure how to go about fixing this
https://community.home-assistant.io/t/finally-announcing-my-suite-of-lovelace-plugins/218584/63?u=hangryman250

**Comment by cscoppafox** [comment]
Same here:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/111901305/236122218-9dbfa704-44f7-41a3-b385-e2a2c52f53d1.png">

**Comment by AarvdH** [comment]
Same here since 2023.5
Tried reinstall and so on... 
![image](https://user-images.githubusercontent.com/94188400/236414647-445bd1b4-7032-4b61-adab-53593add4400.png)

**Comment by aleksey2000** [comment]
As @froman753 mentioned, HA stopped support of Polymer framework. So, source code of plugin should be rewritten with Lit support. Let's hope, @finity69x2 will fix it)

**Comment by wilfredktlr** [comment]
I took a look at it and I got the error to go away and show the buttons. But the original code used `<hui-generic-entity-row>` which I am not familiair with. The problem is that the properties used to display the button cannot be read. If someone has some experience with this let me know. I'll try to take a look at it later tonight.

PS. Here is what I changed. 

I added this code at the top of `light-brightness-preset-row.js`.

```javascript
import {
	LitElement,
	html,
} from "https://unpkg.com/lit-element@2.0.1/lit-element.js?module";
```

And I changed the code below from this:

```javascript
class CustomLightBrightnessRow extends PolymerElement.Element {
	static get template() {
		return PolymerElement.html`
			[...]
```

To this:

```javascript
class CustomLightBrightnessRow extends LitElement {
	render() {
		return html`
			[...]
```

The problem now is getting the HTML to render correctly.

**Comment by finity69x2** [comment]
I'm working on it.

the polymer deprecation caught me off guard with such little notice and I have to figure out how to update it.

**Comment by mkanet** [comment]
@finity69x2 thank you so much.  I reverted back to **Home Assistant 2023.4.5**  from backup until there's a fix.   `light-brightness-preset-row` is an important part of my Home Assistant setup which I depend on every day.

**Comment by maartenhd** [comment]
> @finity69x2 thank you so much. I reverted back to **Home Assistant 2023.4.5** from backup until there's a fix. `light-brightness-preset-row` is an important part of my Home Assistant setup which I depend on every day.

Same here. Not going to rpgrade.

**Comment by wilfredktlr** [comment]
I just upgraded to version 3.0 (released some 4 hours ago) and it solved the problem.

**Comment by mkanet** [comment]
Do we have to manually replace the old `light-brightness-preset-row.js` file with the new one or do we just let HACS update it?

**Comment by wilfredktlr** [comment]
I just updated it, cleared my browser cache and it worked.

**Comment by mkanet** [comment]
@wilfredktlr did you manually replaced the js file or let HAC update it?  If HACs will do it automatically, I can upgrade back to **Home Assistant 2023.5.x**

**Comment by wilfredktlr** [comment]
I was running Home Assistant 2023.5.x and tried to fix it myself by editing the `light-brightness-preset-row.js` files and removing the `light-brightness-preset-row.js.gz` file (otherwise my changes wouldn't show). When it failed and this module has updated I just installed it and after clearing my browser cache it worked.

I suggest you update this module and test it. If it works you can then update Home Assistant to 2023.5.x.

**Comment by mkanet** [comment]
HACS detected the new version...I just let HACS update it.  Then upgraded to Home Assistant 2023.5.0.  No issues so far. @finity69x2 thank you for fixing it so quickly!

**Comment by thrasher204** [comment]
Beta version 3.0 works for me.

**Comment by mkanet** [comment]
@finity69x2 I noticed a weird side effect after upgrading to beta version 3.0.  After upgrading, the "HIGH" button will not stay on the same line, it is moved to the next line.   They have always been on the same line in the last several years until I upgraded to beta 3.0.  It looks like there's a small issue with HTML rendering.

Maybe because CSS style changed from:  `float: right !important;` ---> `float: left !important;` ?

![image](https://user-images.githubusercontent.com/811008/236702516-596b71ac-d6c9-4ed9-a859-4c4cefe93178.png)

Here is another screenshot from another device... there's definitely room to fit the button, however, it still moves over to the next line:
![image](https://user-images.githubusercontent.com/811008/236703557-aee3551d-7bf2-4632-84f3-db3544a7d45a.png)

**How do I force the buttons to stay on the same line (as before) without changing my entire Home Assistant layout?**

Below, is the yaml I've been using, it has not changed at all.  I tried adding/changing `height` and `width` attributes.. but that doesn't resolve the issue.
```
entities:
  - buttonInactiveColor: gray
    customSetpoints: true
    customTheme: true
    entity: light.hue_ambiance_lamp_1
    hiBrightness: 254
    medBrightness: 186
    lowBrightness: 100
    isOnHiColor: '#EAB933'
    isOnMedColor: '#BC9A00'
    isOnLowColor: '#826C00'
    isOffColor: '#59443D'
    name: Light
    reverseButtons: true
    type: custom:light-brightness-preset-row
```

**Comment by finity69x2** [comment]
> After upgrading, the "HIGH" button will not stay on the same line, it is moved to the next line.

I'm not seeing that in my testing.

Do you use a custom column width?

**Comment by mkanet** [comment]
> 

I'm not using a custom column width.  Was there any style changes that would cause it to do that on 2 of my devices?  The issue goes away immediately after I revert back Home Assistant and also this custom card. 

EDIT:  This doesn't happen my web browser is wide or full-screen.  It happens on my mobile phone app as well as web browser on my desktop (half the width of my monitor).

@finity69x2  I just opened a separate issue:  https://github.com/finity69x2/light-brightness-preset-row/issues/36 specific to this.
