### ISSUE TITLE
Add possibility to change Button Text

### ISSUE THREAD

**Issue by briis** [finity69x2/light-brightness-preset-row#4]
Hi,
Thanks for this. Brilliant idea. Would be great if there would be an option to change the text on buttons, so that it can be localised. So the ability to change LOW, MED, HIGH and OFF, to something else.

**Comment by finity69x2** [comment]
@briis 

I understand your need but I'm kind of hesitant to allow that because the next issue I'll get is that the custom text that people are using is too big to fit in the button area. :(

I don't know how to limit the number of characters that could be used so as to not break the layout of everything.

**Comment by deluxestyle** [comment]
would it be possible to add icons (such as the brightness icons from material design icons) instead of an text to the bottoms?
My lovelace setting is in german and with your card I have now a little break in it. Text could be an issue but maybe icons would help

**Comment by finity69x2** [comment]
@deluxestyle 

possibly.

I'm not a real coder so I'll have to try to learn how to do that. :)

**Comment by deluxestyle** [comment]
Great. Thank you
I will have a look as well. But it is over 15 years that I coded JavaScript 😂

**Comment by finity69x2** [comment]
I haven't had any luck trying to figure out how to do this.

I'm going to close this but if you figure something out you can always come back and try it again.
